// Code generated by cmd/api-generator. DO NOT EDIT.

package api

import (
	"github.com/Mrs4s/go-cqhttp/coolq"
	"github.com/Mrs4s/go-cqhttp/global"
	"github.com/Mrs4s/go-cqhttp/pkg/onebot"
)

func (c *Caller) call(action string, spec *onebot.Spec, p Getter) global.MSG {
	if spec.Version == 11 {
		switch action {
		case ".handle_quick_operation":
			p0 := p.Get("context")
			p1 := p.Get("operation")
			return c.bot.CQHandleQuickOperation(p0, p1)
		case "can_send_image":
			return c.bot.CQCanSendImage()
		case "can_send_record":
			return c.bot.CQCanSendRecord()
		case "get_login_info":
			return c.bot.CQGetLoginInfo()
		case "get_version_info":
			return c.bot.CQGetVersionInfo()
		case "send_group_msg":
			p0 := p.Get("group_id").Int()
			p1 := p.Get("message")
			p2 := p.Get("auto_escape").Bool()
			return c.bot.CQSendGroupMessage(p0, p1, p2)
		case "send_msg":
			p0 := p.Get("group_id").Int()
			p1 := p.Get("user_id").Int()
			p2 := p.Get("message")
			p3 := p.Get("message_type").String()
			p4 := p.Get("auto_escape").Bool()
			return c.bot.CQSendMessage(p0, p1, p2, p3, p4)
		case "send_private_msg":
			p0 := p.Get("user_id").Int()
			p1 := p.Get("group_id").Int()
			p2 := p.Get("message")
			p3 := p.Get("auto_escape").Bool()
			return c.bot.CQSendPrivateMessage(p0, p1, p2, p3)
		}
	}
	if spec.Version == 12 {
		switch action {
		case "get_self_info":
			return c.bot.CQGetLoginInfo()
		case "get_version":
			return c.bot.CQGetVersion()
		case "send_message":
			p0 := p.Get("group_id").String()
			p1 := p.Get("user_id").String()
			p2 := p.Get("detail_type").String()
			p3 := p.Get("message")
			return c.bot.CQSendMessageV12(p0, p1, p2, p3)
		}
	}
	switch action {
	case "delete_msg":
		p0 := int32(p.Get("message_id").Int())
		return c.bot.CQDeleteMessage(p0)
	case "download_file":
		p0 := p.Get("url").String()
		p1 := p.Get("headers")
		p2 := int(p.Get("thread_count").Int())
		return c.bot.CQDownloadFile(p0, p1, p2)
	case "get_friend_list":
		return c.bot.CQGetFriendList(spec)
	case "get_group_info":
		p0 := p.Get("group_id").Int()
		p1 := p.Get("no_cache").Bool()
		return c.bot.CQGetGroupInfo(p0, p1, spec)
	case "get_group_list":
		p0 := p.Get("no_cache").Bool()
		return c.bot.CQGetGroupList(p0, spec)
	case "get_group_member_info":
		p0 := p.Get("group_id").Int()
		p1 := p.Get("user_id").Int()
		p2 := p.Get("no_cache").Bool()
		return c.bot.CQGetGroupMemberInfo(p0, p1, p2)
	case "get_group_member_list":
		p0 := p.Get("group_id").Int()
		p1 := p.Get("no_cache").Bool()
		return c.bot.CQGetGroupMemberList(p0, p1)
	case "get_image":
		p0 := p.Get("file").String()
		return c.bot.CQGetImage(p0)
	case "get_msg":
		p0 := int32(p.Get("message_id").Int())
		return c.bot.CQGetMessage(p0)
	case "get_status":
		return c.bot.CQGetStatus(spec)
	case "get_supported_actions":
		return c.bot.CQGetSupportedActions(spec)
	case "reload_event_filter":
		p0 := p.Get("file").String()
		return c.bot.CQReloadEventFilter(p0)
	case "set_friend_add_request":
		p0 := p.Get("flag").String()
		p1 := true
		if pt := p.Get("approve"); pt.Exists() {
			p1 = pt.Bool()
		}
		return c.bot.CQProcessFriendRequest(p0, p1)
	case "set_group_add_request":
		p0 := p.Get("flag").String()
		p1 := p.Get("[sub_type,type].0").String()
		p2 := p.Get("reason").String()
		p3 := true
		if pt := p.Get("approve"); pt.Exists() {
			p3 = pt.Bool()
		}
		return c.bot.CQProcessGroupRequest(p0, p1, p2, p3)
	case "set_group_admin":
		p0 := p.Get("group_id").Int()
		p1 := p.Get("user_id").Int()
		p2 := true
		if pt := p.Get("enable"); pt.Exists() {
			p2 = pt.Bool()
		}
		return c.bot.CQSetGroupAdmin(p0, p1, p2)
	case "set_group_ban":
		p0 := p.Get("group_id").Int()
		p1 := p.Get("user_id").Int()
		p2 := uint32(1800)
		if pt := p.Get("duration"); pt.Exists() {
			p2 = uint32(pt.Uint())
		}
		return c.bot.CQSetGroupBan(p0, p1, p2)
	case "set_group_card":
		p0 := p.Get("group_id").Int()
		p1 := p.Get("user_id").Int()
		p2 := p.Get("card").String()
		return c.bot.CQSetGroupCard(p0, p1, p2)
	case "set_group_kick":
		p0 := p.Get("group_id").Int()
		p1 := p.Get("user_id").Int()
		p2 := p.Get("message").String()
		p3 := p.Get("reject_add_request").Bool()
		return c.bot.CQSetGroupKick(p0, p1, p2, p3)
	case "set_group_leave":
		p0 := p.Get("group_id").Int()
		return c.bot.CQSetGroupLeave(p0)
	case "set_group_name":
		p0 := p.Get("group_id").Int()
		p1 := p.Get("group_name").String()
		return c.bot.CQSetGroupName(p0, p1)
	case "set_group_special_title":
		p0 := p.Get("group_id").Int()
		p1 := p.Get("user_id").Int()
		p2 := p.Get("special_title").String()
		return c.bot.CQSetGroupSpecialTitle(p0, p1, p2)
	case "set_group_whole_ban":
		p0 := p.Get("group_id").Int()
		p1 := true
		if pt := p.Get("enable"); pt.Exists() {
			p1 = pt.Bool()
		}
		return c.bot.CQSetGroupWholeBan(p0, p1)
	}
	return coolq.Failed(404, "API_NOT_FOUND", "API不存在")
}
